2022-04-27 02:42:26.026 [1;31m-ERROR[m  [35m[e: Kafka Source][m [36mo.a.f.r.s.c.SourceCoordinator [m : Uncaught exception in the SplitEnumerator for Source Source: Kafka Source while starting the SplitEnumerator.. Triggering job failover.
org.apache.kafka.common.KafkaException: Failed to construct kafka consumer
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:820) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:666) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:646) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.flink.connector.kafka.source.enumerator.KafkaSourceEnumerator.getKafkaConsumer(KafkaSourceEnumerator.java:421) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.flink.connector.kafka.source.enumerator.KafkaSourceEnumerator.start(KafkaSourceEnumerator.java:150) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.flink.runtime.source.coordinator.SourceCoordinator.lambda$start$0(SourceCoordinator.java:136) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.flink.runtime.source.coordinator.SourceCoordinator.lambda$runInEventLoop$8(SourceCoordinator.java:329) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_332]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_332]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[?:1.8.0_332]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[?:1.8.0_332]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_332]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_332]
	at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_332]
Caused by: org.apache.kafka.common.config.ConfigException: No resolvable bootstrap urls given in bootstrap.servers
	at org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:88) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:47) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:735) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	... 13 more
2022-04-27 02:42:27.027 [1;31m-ERROR[m  [35m[e: Kafka Source][m [36mo.a.f.r.s.c.SourceCoordinator [m : Uncaught exception in the SplitEnumerator for Source Source: Kafka Source while starting the SplitEnumerator.. Triggering job failover.
org.apache.kafka.common.KafkaException: Failed to construct kafka consumer
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:820) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:666) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:646) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.flink.connector.kafka.source.enumerator.KafkaSourceEnumerator.getKafkaConsumer(KafkaSourceEnumerator.java:421) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.flink.connector.kafka.source.enumerator.KafkaSourceEnumerator.start(KafkaSourceEnumerator.java:150) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.flink.runtime.source.coordinator.SourceCoordinator.lambda$start$0(SourceCoordinator.java:136) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.flink.runtime.source.coordinator.SourceCoordinator.lambda$runInEventLoop$8(SourceCoordinator.java:329) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_332]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_332]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[?:1.8.0_332]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[?:1.8.0_332]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_332]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_332]
	at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_332]
Caused by: org.apache.kafka.common.config.ConfigException: No resolvable bootstrap urls given in bootstrap.servers
	at org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:88) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:47) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:735) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	... 13 more
2022-04-27 02:42:28.028 [1;31m-ERROR[m  [35m[e: Kafka Source][m [36mo.a.f.r.s.c.SourceCoordinator [m : Uncaught exception in the SplitEnumerator for Source Source: Kafka Source while starting the SplitEnumerator.. Triggering job failover.
org.apache.kafka.common.KafkaException: Failed to construct kafka consumer
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:820) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:666) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:646) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.flink.connector.kafka.source.enumerator.KafkaSourceEnumerator.getKafkaConsumer(KafkaSourceEnumerator.java:421) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.flink.connector.kafka.source.enumerator.KafkaSourceEnumerator.start(KafkaSourceEnumerator.java:150) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.flink.runtime.source.coordinator.SourceCoordinator.lambda$start$0(SourceCoordinator.java:136) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.flink.runtime.source.coordinator.SourceCoordinator.lambda$runInEventLoop$8(SourceCoordinator.java:329) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_332]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_332]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[?:1.8.0_332]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[?:1.8.0_332]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_332]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_332]
	at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_332]
Caused by: org.apache.kafka.common.config.ConfigException: No resolvable bootstrap urls given in bootstrap.servers
	at org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:88) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:47) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:735) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	... 13 more
2022-04-27 02:42:29.029 [1;31m-ERROR[m  [35m[e: Kafka Source][m [36mo.a.f.r.s.c.SourceCoordinator [m : Uncaught exception in the SplitEnumerator for Source Source: Kafka Source while starting the SplitEnumerator.. Triggering job failover.
org.apache.kafka.common.KafkaException: Failed to construct kafka consumer
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:820) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:666) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:646) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.flink.connector.kafka.source.enumerator.KafkaSourceEnumerator.getKafkaConsumer(KafkaSourceEnumerator.java:421) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.flink.connector.kafka.source.enumerator.KafkaSourceEnumerator.start(KafkaSourceEnumerator.java:150) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.flink.runtime.source.coordinator.SourceCoordinator.lambda$start$0(SourceCoordinator.java:136) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.flink.runtime.source.coordinator.SourceCoordinator.lambda$runInEventLoop$8(SourceCoordinator.java:329) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_332]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_332]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[?:1.8.0_332]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[?:1.8.0_332]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_332]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_332]
	at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_332]
Caused by: org.apache.kafka.common.config.ConfigException: No resolvable bootstrap urls given in bootstrap.servers
	at org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:88) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:47) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:735) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	... 13 more
2022-04-27 02:42:30.030 [1;31m-ERROR[m  [35m[e: Kafka Source][m [36mo.a.f.r.s.c.SourceCoordinator [m : Uncaught exception in the SplitEnumerator for Source Source: Kafka Source while starting the SplitEnumerator.. Triggering job failover.
org.apache.kafka.common.KafkaException: Failed to construct kafka consumer
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:820) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:666) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:646) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.flink.connector.kafka.source.enumerator.KafkaSourceEnumerator.getKafkaConsumer(KafkaSourceEnumerator.java:421) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.flink.connector.kafka.source.enumerator.KafkaSourceEnumerator.start(KafkaSourceEnumerator.java:150) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.flink.runtime.source.coordinator.SourceCoordinator.lambda$start$0(SourceCoordinator.java:136) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.flink.runtime.source.coordinator.SourceCoordinator.lambda$runInEventLoop$8(SourceCoordinator.java:329) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_332]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_332]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[?:1.8.0_332]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[?:1.8.0_332]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_332]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_332]
	at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_332]
Caused by: org.apache.kafka.common.config.ConfigException: No resolvable bootstrap urls given in bootstrap.servers
	at org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:88) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:47) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:735) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	... 13 more
2022-04-27 02:42:31.031 [1;31m-ERROR[m  [35m[e: Kafka Source][m [36mo.a.f.r.s.c.SourceCoordinator [m : Uncaught exception in the SplitEnumerator for Source Source: Kafka Source while starting the SplitEnumerator.. Triggering job failover.
org.apache.kafka.common.KafkaException: Failed to construct kafka consumer
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:820) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:666) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:646) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.flink.connector.kafka.source.enumerator.KafkaSourceEnumerator.getKafkaConsumer(KafkaSourceEnumerator.java:421) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.flink.connector.kafka.source.enumerator.KafkaSourceEnumerator.start(KafkaSourceEnumerator.java:150) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.flink.runtime.source.coordinator.SourceCoordinator.lambda$start$0(SourceCoordinator.java:136) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.flink.runtime.source.coordinator.SourceCoordinator.lambda$runInEventLoop$8(SourceCoordinator.java:329) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_332]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_332]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[?:1.8.0_332]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[?:1.8.0_332]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_332]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_332]
	at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_332]
Caused by: org.apache.kafka.common.config.ConfigException: No resolvable bootstrap urls given in bootstrap.servers
	at org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:88) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:47) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:735) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	... 13 more
2022-04-27 02:42:32.032 [1;31m-ERROR[m  [35m[e: Kafka Source][m [36mo.a.f.r.s.c.SourceCoordinator [m : Uncaught exception in the SplitEnumerator for Source Source: Kafka Source while starting the SplitEnumerator.. Triggering job failover.
org.apache.kafka.common.KafkaException: Failed to construct kafka consumer
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:820) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:666) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:646) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.flink.connector.kafka.source.enumerator.KafkaSourceEnumerator.getKafkaConsumer(KafkaSourceEnumerator.java:421) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.flink.connector.kafka.source.enumerator.KafkaSourceEnumerator.start(KafkaSourceEnumerator.java:150) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.flink.runtime.source.coordinator.SourceCoordinator.lambda$start$0(SourceCoordinator.java:136) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.flink.runtime.source.coordinator.SourceCoordinator.lambda$runInEventLoop$8(SourceCoordinator.java:329) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_332]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_332]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[?:1.8.0_332]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[?:1.8.0_332]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_332]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_332]
	at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_332]
Caused by: org.apache.kafka.common.config.ConfigException: No resolvable bootstrap urls given in bootstrap.servers
	at org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:88) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:47) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:735) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	... 13 more
2022-04-27 02:42:33.033 [1;31m-ERROR[m  [35m[e: Kafka Source][m [36mo.a.f.r.s.c.SourceCoordinator [m : Uncaught exception in the SplitEnumerator for Source Source: Kafka Source while starting the SplitEnumerator.. Triggering job failover.
org.apache.kafka.common.KafkaException: Failed to construct kafka consumer
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:820) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:666) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:646) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.flink.connector.kafka.source.enumerator.KafkaSourceEnumerator.getKafkaConsumer(KafkaSourceEnumerator.java:421) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.flink.connector.kafka.source.enumerator.KafkaSourceEnumerator.start(KafkaSourceEnumerator.java:150) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.flink.runtime.source.coordinator.SourceCoordinator.lambda$start$0(SourceCoordinator.java:136) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.flink.runtime.source.coordinator.SourceCoordinator.lambda$runInEventLoop$8(SourceCoordinator.java:329) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_332]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_332]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[?:1.8.0_332]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[?:1.8.0_332]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_332]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_332]
	at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_332]
Caused by: org.apache.kafka.common.config.ConfigException: No resolvable bootstrap urls given in bootstrap.servers
	at org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:88) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:47) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:735) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	... 13 more
2022-04-27 02:42:34.034 [1;31m-ERROR[m  [35m[e: Kafka Source][m [36mo.a.f.r.s.c.SourceCoordinator [m : Uncaught exception in the SplitEnumerator for Source Source: Kafka Source while starting the SplitEnumerator.. Triggering job failover.
org.apache.kafka.common.KafkaException: Failed to construct kafka consumer
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:820) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:666) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:646) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.flink.connector.kafka.source.enumerator.KafkaSourceEnumerator.getKafkaConsumer(KafkaSourceEnumerator.java:421) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.flink.connector.kafka.source.enumerator.KafkaSourceEnumerator.start(KafkaSourceEnumerator.java:150) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.flink.runtime.source.coordinator.SourceCoordinator.lambda$start$0(SourceCoordinator.java:136) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.flink.runtime.source.coordinator.SourceCoordinator.lambda$runInEventLoop$8(SourceCoordinator.java:329) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_332]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_332]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[?:1.8.0_332]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[?:1.8.0_332]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_332]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_332]
	at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_332]
Caused by: org.apache.kafka.common.config.ConfigException: No resolvable bootstrap urls given in bootstrap.servers
	at org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:88) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:47) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:735) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	... 13 more
2022-04-27 02:42:35.035 [1;31m-ERROR[m  [35m[e: Kafka Source][m [36mo.a.f.r.s.c.SourceCoordinator [m : Uncaught exception in the SplitEnumerator for Source Source: Kafka Source while starting the SplitEnumerator.. Triggering job failover.
org.apache.kafka.common.KafkaException: Failed to construct kafka consumer
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:820) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:666) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:646) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.flink.connector.kafka.source.enumerator.KafkaSourceEnumerator.getKafkaConsumer(KafkaSourceEnumerator.java:421) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.flink.connector.kafka.source.enumerator.KafkaSourceEnumerator.start(KafkaSourceEnumerator.java:150) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.flink.runtime.source.coordinator.SourceCoordinator.lambda$start$0(SourceCoordinator.java:136) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.flink.runtime.source.coordinator.SourceCoordinator.lambda$runInEventLoop$8(SourceCoordinator.java:329) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_332]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_332]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[?:1.8.0_332]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[?:1.8.0_332]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_332]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_332]
	at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_332]
Caused by: org.apache.kafka.common.config.ConfigException: No resolvable bootstrap urls given in bootstrap.servers
	at org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:88) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:47) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:735) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	... 13 more
2022-04-27 02:42:36.036 [1;31m-ERROR[m  [35m[e: Kafka Source][m [36mo.a.f.r.s.c.SourceCoordinator [m : Uncaught exception in the SplitEnumerator for Source Source: Kafka Source while starting the SplitEnumerator.. Triggering job failover.
org.apache.kafka.common.KafkaException: Failed to construct kafka consumer
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:820) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:666) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:646) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.flink.connector.kafka.source.enumerator.KafkaSourceEnumerator.getKafkaConsumer(KafkaSourceEnumerator.java:421) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.flink.connector.kafka.source.enumerator.KafkaSourceEnumerator.start(KafkaSourceEnumerator.java:150) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.flink.runtime.source.coordinator.SourceCoordinator.lambda$start$0(SourceCoordinator.java:136) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.flink.runtime.source.coordinator.SourceCoordinator.lambda$runInEventLoop$8(SourceCoordinator.java:329) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_332]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_332]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[?:1.8.0_332]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[?:1.8.0_332]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_332]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_332]
	at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_332]
Caused by: org.apache.kafka.common.config.ConfigException: No resolvable bootstrap urls given in bootstrap.servers
	at org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:88) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:47) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:735) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	... 13 more
2022-04-27 02:42:37.037 [1;31m-ERROR[m  [35m[e: Kafka Source][m [36mo.a.f.r.s.c.SourceCoordinator [m : Uncaught exception in the SplitEnumerator for Source Source: Kafka Source while starting the SplitEnumerator.. Triggering job failover.
org.apache.kafka.common.KafkaException: Failed to construct kafka consumer
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:820) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:666) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:646) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.flink.connector.kafka.source.enumerator.KafkaSourceEnumerator.getKafkaConsumer(KafkaSourceEnumerator.java:421) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.flink.connector.kafka.source.enumerator.KafkaSourceEnumerator.start(KafkaSourceEnumerator.java:150) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.flink.runtime.source.coordinator.SourceCoordinator.lambda$start$0(SourceCoordinator.java:136) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.flink.runtime.source.coordinator.SourceCoordinator.lambda$runInEventLoop$8(SourceCoordinator.java:329) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_332]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_332]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[?:1.8.0_332]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[?:1.8.0_332]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_332]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_332]
	at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_332]
Caused by: org.apache.kafka.common.config.ConfigException: No resolvable bootstrap urls given in bootstrap.servers
	at org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:88) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:47) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:735) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	... 13 more
2022-04-27 02:42:38.038 [1;31m-ERROR[m  [35m[e: Kafka Source][m [36mo.a.f.r.s.c.SourceCoordinator [m : Uncaught exception in the SplitEnumerator for Source Source: Kafka Source while starting the SplitEnumerator.. Triggering job failover.
org.apache.kafka.common.KafkaException: Failed to construct kafka consumer
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:820) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:666) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:646) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.flink.connector.kafka.source.enumerator.KafkaSourceEnumerator.getKafkaConsumer(KafkaSourceEnumerator.java:421) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.flink.connector.kafka.source.enumerator.KafkaSourceEnumerator.start(KafkaSourceEnumerator.java:150) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.flink.runtime.source.coordinator.SourceCoordinator.lambda$start$0(SourceCoordinator.java:136) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.flink.runtime.source.coordinator.SourceCoordinator.lambda$runInEventLoop$8(SourceCoordinator.java:329) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_332]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_332]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[?:1.8.0_332]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[?:1.8.0_332]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_332]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_332]
	at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_332]
Caused by: org.apache.kafka.common.config.ConfigException: No resolvable bootstrap urls given in bootstrap.servers
	at org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:88) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:47) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:735) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	... 13 more
2022-04-27 02:42:39.039 [1;31m-ERROR[m  [35m[e: Kafka Source][m [36mo.a.f.r.s.c.SourceCoordinator [m : Uncaught exception in the SplitEnumerator for Source Source: Kafka Source while starting the SplitEnumerator.. Triggering job failover.
org.apache.kafka.common.KafkaException: Failed to construct kafka consumer
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:820) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:666) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:646) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.flink.connector.kafka.source.enumerator.KafkaSourceEnumerator.getKafkaConsumer(KafkaSourceEnumerator.java:421) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.flink.connector.kafka.source.enumerator.KafkaSourceEnumerator.start(KafkaSourceEnumerator.java:150) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.flink.runtime.source.coordinator.SourceCoordinator.lambda$start$0(SourceCoordinator.java:136) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.flink.runtime.source.coordinator.SourceCoordinator.lambda$runInEventLoop$8(SourceCoordinator.java:329) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_332]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_332]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[?:1.8.0_332]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[?:1.8.0_332]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_332]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_332]
	at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_332]
Caused by: org.apache.kafka.common.config.ConfigException: No resolvable bootstrap urls given in bootstrap.servers
	at org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:88) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:47) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:735) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	... 13 more
2022-04-27 02:42:40.040 [1;31m-ERROR[m  [35m[e: Kafka Source][m [36mo.a.f.r.s.c.SourceCoordinator [m : Uncaught exception in the SplitEnumerator for Source Source: Kafka Source while starting the SplitEnumerator.. Triggering job failover.
org.apache.kafka.common.KafkaException: Failed to construct kafka consumer
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:820) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:666) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:646) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.flink.connector.kafka.source.enumerator.KafkaSourceEnumerator.getKafkaConsumer(KafkaSourceEnumerator.java:421) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.flink.connector.kafka.source.enumerator.KafkaSourceEnumerator.start(KafkaSourceEnumerator.java:150) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.flink.runtime.source.coordinator.SourceCoordinator.lambda$start$0(SourceCoordinator.java:136) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.flink.runtime.source.coordinator.SourceCoordinator.lambda$runInEventLoop$8(SourceCoordinator.java:329) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_332]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_332]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[?:1.8.0_332]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[?:1.8.0_332]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_332]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_332]
	at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_332]
Caused by: org.apache.kafka.common.config.ConfigException: No resolvable bootstrap urls given in bootstrap.servers
	at org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:88) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:47) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:735) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	... 13 more
2022-04-27 02:42:41.041 [1;31m-ERROR[m  [35m[e: Kafka Source][m [36mo.a.f.r.s.c.SourceCoordinator [m : Uncaught exception in the SplitEnumerator for Source Source: Kafka Source while starting the SplitEnumerator.. Triggering job failover.
org.apache.kafka.common.KafkaException: Failed to construct kafka consumer
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:820) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:666) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:646) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.flink.connector.kafka.source.enumerator.KafkaSourceEnumerator.getKafkaConsumer(KafkaSourceEnumerator.java:421) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.flink.connector.kafka.source.enumerator.KafkaSourceEnumerator.start(KafkaSourceEnumerator.java:150) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.flink.runtime.source.coordinator.SourceCoordinator.lambda$start$0(SourceCoordinator.java:136) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.flink.runtime.source.coordinator.SourceCoordinator.lambda$runInEventLoop$8(SourceCoordinator.java:329) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_332]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_332]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[?:1.8.0_332]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[?:1.8.0_332]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_332]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_332]
	at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_332]
Caused by: org.apache.kafka.common.config.ConfigException: No resolvable bootstrap urls given in bootstrap.servers
	at org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:88) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:47) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:735) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	... 13 more
2022-04-27 02:42:43.043 [1;31m-ERROR[m  [35m[e: Kafka Source][m [36mo.a.f.r.s.c.SourceCoordinator [m : Uncaught exception in the SplitEnumerator for Source Source: Kafka Source while starting the SplitEnumerator.. Triggering job failover.
org.apache.kafka.common.KafkaException: Failed to construct kafka consumer
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:820) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:666) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:646) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.flink.connector.kafka.source.enumerator.KafkaSourceEnumerator.getKafkaConsumer(KafkaSourceEnumerator.java:421) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.flink.connector.kafka.source.enumerator.KafkaSourceEnumerator.start(KafkaSourceEnumerator.java:150) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.flink.runtime.source.coordinator.SourceCoordinator.lambda$start$0(SourceCoordinator.java:136) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.flink.runtime.source.coordinator.SourceCoordinator.lambda$runInEventLoop$8(SourceCoordinator.java:329) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_332]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_332]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[?:1.8.0_332]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[?:1.8.0_332]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_332]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_332]
	at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_332]
Caused by: org.apache.kafka.common.config.ConfigException: No resolvable bootstrap urls given in bootstrap.servers
	at org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:88) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:47) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:735) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	... 13 more
2022-04-27 02:42:44.044 [1;31m-ERROR[m  [35m[e: Kafka Source][m [36mo.a.f.r.s.c.SourceCoordinator [m : Uncaught exception in the SplitEnumerator for Source Source: Kafka Source while starting the SplitEnumerator.. Triggering job failover.
org.apache.kafka.common.KafkaException: Failed to construct kafka consumer
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:820) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:666) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:646) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.flink.connector.kafka.source.enumerator.KafkaSourceEnumerator.getKafkaConsumer(KafkaSourceEnumerator.java:421) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.flink.connector.kafka.source.enumerator.KafkaSourceEnumerator.start(KafkaSourceEnumerator.java:150) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.flink.runtime.source.coordinator.SourceCoordinator.lambda$start$0(SourceCoordinator.java:136) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.flink.runtime.source.coordinator.SourceCoordinator.lambda$runInEventLoop$8(SourceCoordinator.java:329) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_332]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_332]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[?:1.8.0_332]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[?:1.8.0_332]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_332]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_332]
	at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_332]
Caused by: org.apache.kafka.common.config.ConfigException: No resolvable bootstrap urls given in bootstrap.servers
	at org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:88) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:47) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:735) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	... 13 more
2022-04-27 02:42:45.045 [1;31m-ERROR[m  [35m[e: Kafka Source][m [36mo.a.f.r.s.c.SourceCoordinator [m : Uncaught exception in the SplitEnumerator for Source Source: Kafka Source while starting the SplitEnumerator.. Triggering job failover.
org.apache.kafka.common.KafkaException: Failed to construct kafka consumer
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:820) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:666) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:646) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.flink.connector.kafka.source.enumerator.KafkaSourceEnumerator.getKafkaConsumer(KafkaSourceEnumerator.java:421) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.flink.connector.kafka.source.enumerator.KafkaSourceEnumerator.start(KafkaSourceEnumerator.java:150) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.flink.runtime.source.coordinator.SourceCoordinator.lambda$start$0(SourceCoordinator.java:136) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.flink.runtime.source.coordinator.SourceCoordinator.lambda$runInEventLoop$8(SourceCoordinator.java:329) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_332]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_332]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[?:1.8.0_332]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[?:1.8.0_332]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_332]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_332]
	at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_332]
Caused by: org.apache.kafka.common.config.ConfigException: No resolvable bootstrap urls given in bootstrap.servers
	at org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:88) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:47) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:735) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	... 13 more
2022-04-27 02:42:46.046 [1;31m-ERROR[m  [35m[e: Kafka Source][m [36mo.a.f.r.s.c.SourceCoordinator [m : Uncaught exception in the SplitEnumerator for Source Source: Kafka Source while starting the SplitEnumerator.. Triggering job failover.
org.apache.kafka.common.KafkaException: Failed to construct kafka consumer
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:820) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:666) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:646) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.flink.connector.kafka.source.enumerator.KafkaSourceEnumerator.getKafkaConsumer(KafkaSourceEnumerator.java:421) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.flink.connector.kafka.source.enumerator.KafkaSourceEnumerator.start(KafkaSourceEnumerator.java:150) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.flink.runtime.source.coordinator.SourceCoordinator.lambda$start$0(SourceCoordinator.java:136) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.flink.runtime.source.coordinator.SourceCoordinator.lambda$runInEventLoop$8(SourceCoordinator.java:329) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_332]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_332]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[?:1.8.0_332]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[?:1.8.0_332]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_332]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_332]
	at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_332]
Caused by: org.apache.kafka.common.config.ConfigException: No resolvable bootstrap urls given in bootstrap.servers
	at org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:88) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:47) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:735) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	... 13 more
2022-04-27 02:42:47.047 [1;31m-ERROR[m  [35m[e: Kafka Source][m [36mo.a.f.r.s.c.SourceCoordinator [m : Uncaught exception in the SplitEnumerator for Source Source: Kafka Source while starting the SplitEnumerator.. Triggering job failover.
org.apache.kafka.common.KafkaException: Failed to construct kafka consumer
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:820) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:666) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:646) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.flink.connector.kafka.source.enumerator.KafkaSourceEnumerator.getKafkaConsumer(KafkaSourceEnumerator.java:421) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.flink.connector.kafka.source.enumerator.KafkaSourceEnumerator.start(KafkaSourceEnumerator.java:150) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.flink.runtime.source.coordinator.SourceCoordinator.lambda$start$0(SourceCoordinator.java:136) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.flink.runtime.source.coordinator.SourceCoordinator.lambda$runInEventLoop$8(SourceCoordinator.java:329) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_332]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_332]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[?:1.8.0_332]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[?:1.8.0_332]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_332]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_332]
	at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_332]
Caused by: org.apache.kafka.common.config.ConfigException: No resolvable bootstrap urls given in bootstrap.servers
	at org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:88) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:47) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:735) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	... 13 more
2022-04-27 02:42:48.048 [1;31m-ERROR[m  [35m[e: Kafka Source][m [36mo.a.f.r.s.c.SourceCoordinator [m : Uncaught exception in the SplitEnumerator for Source Source: Kafka Source while starting the SplitEnumerator.. Triggering job failover.
org.apache.kafka.common.KafkaException: Failed to construct kafka consumer
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:820) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:666) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:646) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.flink.connector.kafka.source.enumerator.KafkaSourceEnumerator.getKafkaConsumer(KafkaSourceEnumerator.java:421) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.flink.connector.kafka.source.enumerator.KafkaSourceEnumerator.start(KafkaSourceEnumerator.java:150) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.flink.runtime.source.coordinator.SourceCoordinator.lambda$start$0(SourceCoordinator.java:136) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.flink.runtime.source.coordinator.SourceCoordinator.lambda$runInEventLoop$8(SourceCoordinator.java:329) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_332]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_332]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[?:1.8.0_332]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[?:1.8.0_332]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_332]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_332]
	at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_332]
Caused by: org.apache.kafka.common.config.ConfigException: No resolvable bootstrap urls given in bootstrap.servers
	at org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:88) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:47) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:735) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	... 13 more
2022-04-27 02:42:49.049 [1;31m-ERROR[m  [35m[e: Kafka Source][m [36mo.a.f.r.s.c.SourceCoordinator [m : Uncaught exception in the SplitEnumerator for Source Source: Kafka Source while starting the SplitEnumerator.. Triggering job failover.
org.apache.kafka.common.KafkaException: Failed to construct kafka consumer
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:820) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:666) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:646) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.flink.connector.kafka.source.enumerator.KafkaSourceEnumerator.getKafkaConsumer(KafkaSourceEnumerator.java:421) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.flink.connector.kafka.source.enumerator.KafkaSourceEnumerator.start(KafkaSourceEnumerator.java:150) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.flink.runtime.source.coordinator.SourceCoordinator.lambda$start$0(SourceCoordinator.java:136) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.flink.runtime.source.coordinator.SourceCoordinator.lambda$runInEventLoop$8(SourceCoordinator.java:329) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_332]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_332]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[?:1.8.0_332]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[?:1.8.0_332]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_332]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_332]
	at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_332]
Caused by: org.apache.kafka.common.config.ConfigException: No resolvable bootstrap urls given in bootstrap.servers
	at org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:88) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:47) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:735) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	... 13 more
2022-04-27 02:42:50.050 [1;31m-ERROR[m  [35m[e: Kafka Source][m [36mo.a.f.r.s.c.SourceCoordinator [m : Uncaught exception in the SplitEnumerator for Source Source: Kafka Source while starting the SplitEnumerator.. Triggering job failover.
org.apache.kafka.common.KafkaException: Failed to construct kafka consumer
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:820) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:666) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:646) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.flink.connector.kafka.source.enumerator.KafkaSourceEnumerator.getKafkaConsumer(KafkaSourceEnumerator.java:421) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.flink.connector.kafka.source.enumerator.KafkaSourceEnumerator.start(KafkaSourceEnumerator.java:150) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.flink.runtime.source.coordinator.SourceCoordinator.lambda$start$0(SourceCoordinator.java:136) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.flink.runtime.source.coordinator.SourceCoordinator.lambda$runInEventLoop$8(SourceCoordinator.java:329) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_332]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_332]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[?:1.8.0_332]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[?:1.8.0_332]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_332]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_332]
	at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_332]
Caused by: org.apache.kafka.common.config.ConfigException: No resolvable bootstrap urls given in bootstrap.servers
	at org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:88) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:47) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:735) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	... 13 more
2022-04-27 02:42:51.051 [1;31m-ERROR[m  [35m[e: Kafka Source][m [36mo.a.f.r.s.c.SourceCoordinator [m : Uncaught exception in the SplitEnumerator for Source Source: Kafka Source while starting the SplitEnumerator.. Triggering job failover.
org.apache.kafka.common.KafkaException: Failed to construct kafka consumer
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:820) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:666) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:646) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.flink.connector.kafka.source.enumerator.KafkaSourceEnumerator.getKafkaConsumer(KafkaSourceEnumerator.java:421) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.flink.connector.kafka.source.enumerator.KafkaSourceEnumerator.start(KafkaSourceEnumerator.java:150) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.flink.runtime.source.coordinator.SourceCoordinator.lambda$start$0(SourceCoordinator.java:136) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.flink.runtime.source.coordinator.SourceCoordinator.lambda$runInEventLoop$8(SourceCoordinator.java:329) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_332]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_332]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[?:1.8.0_332]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[?:1.8.0_332]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_332]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_332]
	at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_332]
Caused by: org.apache.kafka.common.config.ConfigException: No resolvable bootstrap urls given in bootstrap.servers
	at org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:88) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:47) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:735) ~[flink-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	... 13 more
